### ISSUE TITLE
Fix Password Update Bug

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Auth-Server#44]
### Description 
There is an issue when trying to update Lif Account password. The server will throw a `500 Internal Server Error`. Here is the error: 
```bash
2023-11-23 20:53:43 authserver-web-1  | INFO:     172.21.0.1:51494 - "POST /lif_password_update HTTP/1.1" 500 Internal Server Error
2023-11-23 20:53:43 authserver-web-1  | ERROR:    Exception in ASGI application
2023-11-23 20:53:43 authserver-web-1  | Traceback (most recent call last):
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-11-23 20:53:43 authserver-web-1  |     result = await app(  # type: ignore[func-returns-value]
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-11-23 20:53:43 authserver-web-1  |     return await self.app(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await super().__call__(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await self.middleware_stack(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-23 20:53:43 authserver-web-1  |     raise exc
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await self.app(scope, receive, _send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2023-11-23 20:53:43 authserver-web-1  |     await self.app(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-23 20:53:43 authserver-web-1  |     raise exc
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await self.app(scope, receive, sender)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-23 20:53:43 authserver-web-1  |     raise e
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await self.app(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
2023-11-23 20:53:43 authserver-web-1  |     await route.handle(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
2023-11-23 20:53:43 authserver-web-1  |     await self.app(scope, receive, send)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
2023-11-23 20:53:43 authserver-web-1  |     response = await func(request)
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
2023-11-23 20:53:43 authserver-web-1  |     raw_response = await run_endpoint_function(
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
2023-11-23 20:53:43 authserver-web-1  |     return await dependant.call(**values)
2023-11-23 20:53:43 authserver-web-1  |   File "/app/auth_server.py", line 497, in lif_password_update
2023-11-23 20:53:43 authserver-web-1  |     password_hash = hasher.get_hash_with_database_salt(username=username, password=current_password)
2023-11-23 20:53:43 authserver-web-1  |   File "/app/utils/password_hasher.py", line 9, in get_hash_with_database_salt
2023-11-23 20:53:43 authserver-web-1  |     salt = database.get_password_salt(username)
2023-11-23 20:53:43 authserver-web-1  |   File "/app/utils/db_interface.py", line 71, in get_password_salt
2023-11-23 20:53:43 authserver-web-1  |     connect_to_database()
2023-11-23 20:53:43 authserver-web-1  |   File "/app/utils/db_interface.py", line 35, in connect_to_database
2023-11-23 20:53:43 authserver-web-1  |     if not conn.is_connected():
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 322, in is_connected
2023-11-23 20:53:43 authserver-web-1  |     self.handle_unread_result()
2023-11-23 20:53:43 authserver-web-1  |   File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 932, in handle_unread_result
2023-11-23 20:53:43 authserver-web-1  |     raise InternalError("Unread result found")
2023-11-23 20:53:43 authserver-web-1  | mysql.connector.errors.InternalError: Unread result found
```

### To Reproduce
1. Make a POST request to http://SERVER_URL/lif_password_update

### Expected behavior
The server (if auth successful) should return a `200 Updated Password` response. 

### Platform
 - OS: Linux/Docker
 - Version: 1.3.2

**Comment by Superior126** [comment]
### Update
This is not actually an issue with the password update route. Rather, it is a problem with being able to create two accounts with the same username that causes this error. That issue is here: #45
